[build]
bin = "tmp/app"
cmd = "go build -tags sqlite_fts5,sqlite_math_functions -o ./tmp/app ./cmd/app"
stop_on_error = true

[log]
silent = true

[misc]
clean_on_exit = true

[proxy]
enabled = true
proxy_port = 8081
app_port = 8080
