services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access
      MINIO_ROOT_PASSWORD: secretsecret
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

  minio-test:
    image: maragudk/minio-ci
    environment:
      MINIO_ROOT_USER: access
      MINIO_ROOT_PASSWORD: secretsecret
    ports:
      - "${MINIO_TEST_PORT:-9002}:9000"

volumes:
  minio:
